import '../models/models.dart';

class DataService {
  final List<Centre> centres = [
    const Centre(
      id: 'A',
      name: 'Centre A',
      address: 'Main Procurement Yard',
      lat: 28.61,
      lng: 77.10,
      capacity: 100,
      currentLoad: 0,
      processingRate: 0,
      queue: 0,
      activeStaff: 4,
      staffTotal: 6,
      weighbridgesWorking: 1,
      weighbridgesTotal: 2,
      status: CentreStatus.normal,
      qualityTestingOk: true,
      storageOk: true,
      transportOk: true,
    ),
    const Centre(
      id: 'B',
      name: 'Centre B',
      address: 'North Village Procurement Yard',
      lat: 28.64,
      lng: 77.13,
      capacity: 100,
      currentLoad: 0,
      processingRate: 12,
      queue: 0,
      activeStaff: 6,
      staffTotal: 7,
      weighbridgesWorking: 2,
      weighbridgesTotal: 2,
      status: CentreStatus.normal,
      qualityTestingOk: true,
      storageOk: true,
      transportOk: true,
    ),
    const Centre(
      id: 'C',
      name: 'Centre C',
      address: 'Canal Road Procurement Yard',
      lat: 28.58,
      lng: 77.16,
      capacity: 100,
      currentLoad: 0,
      processingRate: 10,
      queue: 0,
      activeStaff: 5,
      staffTotal: 6,
      weighbridgesWorking: 2,
      weighbridgesTotal: 2,
      status: CentreStatus.normal,
      qualityTestingOk: true,
      storageOk: true,
      transportOk: true,
    ),
    const Centre(
      id: 'D',
      name: 'Centre D',
      address: 'East Block Procurement Yard',
      lat: 28.62,
      lng: 77.20,
      capacity: 100,
      currentLoad: 0,
      processingRate: 11,
      queue: 0,
      activeStaff: 5,
      staffTotal: 6,
      weighbridgesWorking: 2,
      weighbridgesTotal: 2,
      status: CentreStatus.normal,
      qualityTestingOk: true,
      storageOk: true,
      transportOk: true,
    ),
  ];

  // Farmer records are loaded from Supabase. The local list intentionally
  // starts empty so the Government app never shows stale or fake farmers.
  final List<Farmer> farmers = <Farmer>[];
}
